image: node:latest

variables:
  PAGES_BRANCH: master

#include:
#   - template: Code-Quality.gitlab-ci.yml


#code_quality:
#  artifacts:
#    paths: [gl-code-quality-report.json]

stages:
#  - test
  - make_dev
  - pages

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - node_modules/  

make_dev:
  stage: make_dev
  script: 
    - npm install
    - npm run-script ci-dev
  artifacts:
    paths:
      - dev

pages:
  stage: pages
  rules:
    - if: '$CI_COMMIT_REF_NAME == $PAGES_BRANCH'
      when: always
    - when: never
  script:
    - npm install
    - cp -r dev public
  artifacts:
    paths:
      - public
